"""
Django settings for maast_web project.

Generated by 'django-admin startproject' using Django 5.0rc1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

from decouple import config
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)
API_LOCATION = config("API_LOCATION", default="Docker", cast=str)

if API_LOCATION == "Docker":
    API_HOST = config("DOCKER_API_HOST")
else:
    API_HOST = config("REMOTE_API_HOST")

if DEBUG:
    SITE_DOMAIN = config("DEVELOPMENT_SITE_DOMAIN")
else:
    SITE_DOMAIN = config("PRODUCTION_SITE_DOMAIN")

ALLOWED_HOSTS = config("ALLOWED_HOSTS").split(" ")
INTERNAL_IPS = ["127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    # Local
    "maast.apps.MaastConfig",
    "blog.apps.BlogConfig",
    "pages",
    # Third-party
    "tailwind",
    "theme",
    "django_browser_reload",
    "meta",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DEBUG:
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]

ROOT_URLCONF = "maast_web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "maast/templates",
            BASE_DIR / "theme/templates",
            BASE_DIR / "blog/templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "maast_web.wsgi.application"

# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "maast.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Secure the application

if not DEBUG:
    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT")
    SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE")
    SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS")
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config("SECURE_HSTS_INCLUDE_SUBDOMAINS")
    SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD")
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/dev/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom configurations

# Whitenoise settings

# These settings provide support for favicons and other browser icons.
# See https://adamj.eu/tech/2022/01/18/how-to-add-a-favicon-to-your-django-site/ for more details on this approach.
WHITENOISE_ROOT = BASE_DIR / "static_nonversioned"
if not DEBUG:
    WHITENOISE_MAX_AGE = 60 * 60 * 24  # one day

# Tailwind CSS
TAILWIND_APP_NAME = "theme"

# django-meta settings
META_SITE_PROTOCOL = "https"
META_SITE_DOMAIN = "records.themnaa.org"
META_SITE_TYPE = "website"
META_SITE_NAME = "MAA Score Tabulator"
META_INCLUDE_KEYWORDS = [
    "archery",
    "minnesota archers alliance",
    "maa",
    "state records",
    "target archery",
    "nfaa",
    "national field archery association",
    "usa archery",
    "s3da",
    "scholastic 3d archery",
]
META_DEFAULT_KEYWORDS = [
    "archery",
    "minnesota archers alliance",
    "maa",
    "state records",
    "target archery",
    "nfaa",
    "national field archery association",
    "usa archery",
    "s3da",
    "scholastic 3d archery",
]
META_USE_OG_PROPERTIES = True
META_USE_TWITTER_PROPERTIES = False
META_USE_TITLE_TAG = True
META_DEFAULT_IMAGE = "/static/img/MAAST-og.png"
