# Generated by Django 5.0 on 2023-12-15 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteupdateblog',
            options={'verbose_name': 'Site Update'},
        ),
    ]
